# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# Modifications:
#   * workflow_dispatch added to allow manual triggering of the workflow
#   * trigger branches changed
#   * API key secrets.SECRET_EPIPROCESS_GHACTIONS_DELPHI_EPIDATA_KEY
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    # only build docs on the main repository and not forks
    if: github.repository_owner == 'cmu-delphi'
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      DELPHI_EPIDATA_KEY: ${{ secrets.SECRET_EPIPROCESS_GHACTIONS_DELPHI_EPIDATA_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::., any::cli
          needs: website

      - name: Build site
# our versioning system+dev branch doesn't match the requirements for
        # develop mode = auto
        run: |
           target_ref <- "${{ github.event_name == 'pull_request' && github.base_ref || github.ref }}"
           override <- if (target_ref == "main" || target_ref == "refs/heads/main") {
             list(development = list(mode = "release"))
           } else if (target_ref == "dev" || target_ref == "refs/heads/dev") {
             list(development = list(mode = "devel"))
           } else {
             stop("Unexpected target_ref: ", target_ref)
           }
           pkg <- pkgdown::as_pkgdown(".", override = override)
           cli::cli_rule("Cleaning files from old site...")
           pkgdown::clean_site(pkg)
           pkgdown::build_site(pkg, preview = FALSE, install = FALSE, new_process = FALSE)
           pkgdown:::build_github_pages(pkg)
        shell: Rscript {0}

      - name: Deploy to GitHub pages ðŸš€
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
